theme: rohitjain00/dev-portfolio-blog
author_name: "Shakil Ansari"
resume_url: "/assets/ShakilAnsari_Resume.pdf"
description: "Entry-level Data Science Practitioner | NLP · Time Series · ML"
url: "https://ansareze.github.io"
github_username: "Ansareze"
kaggle_username: "shakilansari"
tableau_url: "https://public.tableau.com/profile/shakil.ansari"
